-- Author: nic547
create type tk_vehicle_type as enum ('wagon', 'locomotive', 'multipleunit');
CREATE TYPE epoch AS ENUM ('i', 'ii', 'iii', 'iv', 'v', 'vi');

----------------------------
--Lookup Tables
----------------------------
CREATE TABLE manufacturer (
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT NOT NULL UNIQUE
);

CREATE TABLE proto_manufacturer (
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT NOT NULL UNIQUE
);

CREATE TABLE proto_rw_company (-- Railway companies, for the user and owner of the stock
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT NOT NULL UNIQUE
);

----------------------------
-- Tables
----------------------------

CREATE TABLE proto_class (
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT NOT NULL UNIQUE,
    vehicle_type				tk_vehicle_type,
	proto_manufacturer			INTEGER REFERENCES proto_manufacturer,
	proto_weight				INTEGER,
	proto_speed					SMALLINT,
	engine_tractive_effort		SMALLINT,
	egine_power					SMALLINT
);

CREATE TABLE model_item (
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT,
	image						BYTEA,
    image_preview               BYTEA,
	manufacturer				INTEGER REFERENCES manufacturer(id),
	item_code					TEXT,	
    proto_class                 INTEGER REFERENCES proto_class(id),
	proto_serial_number			TEXT,
	proto_owner					INTEGER REFERENCES proto_rw_company(id),
	proto_user					INTEGER REFERENCES proto_rw_company(id),
    epoch						epoch
);

CREATE TABLE item (
	id							INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name						TEXT, -- Only for special names, otherwise use the name from the model_item
	model_item					INTEGER REFERENCES model_item(id),
	image						BYTEA,
    image_preview               BYTEA,
	price						MONEY,
	date_purchased				DATE,
	notes						TEXT,
	dcc							INTEGER
);